# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/osx-64/blas-1.0-mkl.conda
https://repo.anaconda.com/pkgs/main/osx-64/bzip2-1.0.8-h1de35cc_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/ca-certificates-2021.9.30-hecd8cb5_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/intel-openmp-2021.3.0-hecd8cb5_3375.conda
https://repo.anaconda.com/pkgs/main/osx-64/jpeg-9d-h9ed2024_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libcxx-12.0.0-h2f01273_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libgfortran-3.0.1-h93005f0_2.conda
https://repo.anaconda.com/pkgs/main/osx-64/libiconv-1.16-h1de35cc_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libopus-1.3.1-h1de35cc_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libsodium-1.0.18-h1de35cc_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libwebp-base-1.2.0-h9ed2024_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/llvm-openmp-12.0.0-h0dcd299_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/pixman-0.40.0-h9ed2024_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/xz-5.2.5-h1de35cc_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/yaml-0.2.5-haf1e3a3_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/zlib-1.2.11-h1de35cc_3.conda
https://repo.anaconda.com/pkgs/main/osx-64/brotli-1.0.9-hb1e8313_2.conda
https://repo.anaconda.com/pkgs/main/osx-64/expat-2.4.1-h23ab428_2.conda
https://repo.anaconda.com/pkgs/main/osx-64/graphite2-1.3.14-h38d11af_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/hdf5-1.10.2-hfa1e0ec_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/icu-58.2-h0a44026_3.conda
https://repo.anaconda.com/pkgs/main/osx-64/jasper-2.0.14-h0129ec2_2.conda
https://repo.anaconda.com/pkgs/main/osx-64/libffi-3.3-hb1e8313_2.conda
https://repo.anaconda.com/pkgs/main/osx-64/libpng-1.6.37-ha441bb4_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libvpx-1.7.0-h378b8a2_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/lz4-c-1.9.3-h23ab428_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/mkl-2021.3.0-hecd8cb5_517.conda
https://repo.anaconda.com/pkgs/main/osx-64/ncurses-6.2-h0a44026_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/openssl-1.1.1l-h9ed2024_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/pcre-8.45-h23ab428_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/tk-8.6.11-h7bc2e8c_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/zeromq-4.3.4-h23ab428_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/freetype-2.10.4-ha233b18_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libxml2-2.9.12-hcdb78fc_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/readline-8.1-h9ed2024_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/zstd-1.4.9-h322a384_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/ffmpeg-4.0-h01ea3c9_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/fontconfig-2.13.1-ha9ee91d_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/gettext-0.21.0-h7535e17_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libtiff-4.2.0-h87d7836_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/sqlite-3.36.0-hce871da_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/glib-2.69.1-hdf23fa2_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/lcms2-2.12-hf1fd2bf_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/openjpeg-2.4.0-h66ea3da_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/python-3.7.11-h88f2d9e_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/qt-5.9.7-h468cd18_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/appnope-0.1.2-py37hecd8cb5_1001.conda
https://repo.anaconda.com/pkgs/main/osx-64/async_generator-1.10-py37h28b3542_0.conda
https://repo.anaconda.com/pkgs/main/noarch/attrs-21.2.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/backcall-0.2.0-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/cairo-1.16.0-h8023c5d_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/certifi-2021.10.8-py37hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/cloudpickle-2.0.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/dbus-1.13.18-h18a8e69_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/debugpy-1.4.1-py37h23ab428_0.conda
https://repo.anaconda.com/pkgs/main/noarch/decorator-5.1.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/defusedxml-0.7.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/entrypoints-0.3-py37_0.conda
https://repo.anaconda.com/pkgs/main/noarch/fsspec-2021.8.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/ipython_genutils-0.2.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/noarch/jupyterlab_widgets-1.0.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/kiwisolver-1.3.1-py37h23ab428_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/locket-0.2.1-py37hecd8cb5_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/markupsafe-2.0.1-py37h9ed2024_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/mistune-0.8.4-py37h1de35cc_0.conda
https://repo.anaconda.com/pkgs/main/noarch/munkres-1.1.4-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/nest-asyncio-1.5.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/networkx-2.6.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/olefile-0.46-py37_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/pandocfilters-1.4.3-py37hecd8cb5_1.conda
https://repo.anaconda.com/pkgs/main/noarch/parso-0.8.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pickleshare-0.7.5-pyhd3eb1b0_1003.conda
https://repo.anaconda.com/pkgs/main/noarch/prometheus_client-0.11.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/ptyprocess-0.7.0-pyhd3eb1b0_2.conda
https://repo.anaconda.com/pkgs/main/noarch/pycparser-2.20-py_2.conda
https://repo.anaconda.com/pkgs/main/noarch/pyparsing-2.4.7-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/pyrsistent-0.17.3-py37haf1e3a3_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/pyyaml-5.4.1-py37h9ed2024_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/pyzmq-22.2.1-py37h23ab428_1.conda
https://repo.anaconda.com/pkgs/main/noarch/qtpy-1.10.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/send2trash-1.8.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/sip-4.19.8-py37h0a44026_0.conda
https://repo.anaconda.com/pkgs/main/noarch/six-1.16.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/testpath-0.5.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/toolz-0.11.1-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/tornado-6.1-py37h9ed2024_0.conda
https://repo.anaconda.com/pkgs/main/noarch/traitlets-5.1.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/typing_extensions-3.10.0.2-pyh06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/wcwidth-0.2.5-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/webencodings-0.5.1-py37_1.conda
https://repo.anaconda.com/pkgs/main/noarch/wheel-0.37.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/noarch/zipp-3.6.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/cffi-1.14.6-py37h2125817_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/cycler-0.10.0-py37_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/cytoolz-0.11.0-py37haf1e3a3_0.conda
https://repo.anaconda.com/pkgs/main/noarch/fonttools-4.25.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/harfbuzz-1.8.8-hb8d4a28_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/importlib-metadata-4.8.1-py37hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/jedi-0.18.0-py37hecd8cb5_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/jupyter_core-4.8.1-py37hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/matplotlib-inline-0.1.2-pyhd3eb1b0_2.conda
https://repo.anaconda.com/pkgs/main/osx-64/mkl-service-2.4.0-py37h9ed2024_0.conda
https://repo.anaconda.com/pkgs/main/noarch/packaging-21.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/partd-1.2.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pexpect-4.8.0-pyhd3eb1b0_3.conda
https://repo.anaconda.com/pkgs/main/osx-64/pillow-8.3.1-py37ha4cf6ea_0.conda
https://repo.anaconda.com/pkgs/main/noarch/prompt-toolkit-3.0.20-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/pyqt-5.9.2-py37h655552a_2.conda
https://repo.anaconda.com/pkgs/main/noarch/python-dateutil-2.8.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/setuptools-58.0.4-py37hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/terminado-0.9.4-py37hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/argon2-cffi-20.1.0-py37h9ed2024_1.conda
https://repo.anaconda.com/pkgs/main/noarch/bleach-4.0.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/dask-core-2021.8.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/importlib_metadata-4.8.1-hd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/jinja2-3.0.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/jupyter_client-7.0.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libopencv-3.4.2-h7c891bd_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/numpy-base-1.20.3-py37he0bd621_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/pip-21.0.1-py37hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/prompt_toolkit-3.0.20-hd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pygments-2.10.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/argcomplete-1.12.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/ipython-7.27.0-py37h01d92e1_0.conda
https://repo.anaconda.com/pkgs/main/noarch/jsonschema-3.2.0-pyhd3eb1b0_2.conda
https://repo.anaconda.com/pkgs/main/noarch/jupyterlab_pygments-0.1.2-py_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/ipykernel-6.4.1-py37hecd8cb5_1.conda
https://repo.anaconda.com/pkgs/main/noarch/nbformat-5.1.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/jupyter_console-6.4.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/nbclient-0.5.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/qtconsole-5.1.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/nbconvert-6.1.0-py37hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/notebook-6.4.3-py37hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/widgetsnbextension-3.5.1-py37_0.conda
https://repo.anaconda.com/pkgs/main/noarch/ipywidgets-7.6.4-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/jupyter-1.0.0-py37_7.conda
https://repo.anaconda.com/pkgs/main/noarch/imageio-2.9.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/matplotlib-3.4.2-py37hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/matplotlib-base-3.4.2-py37h8b3ea08_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/mkl_fft-1.3.0-py37h4a7008c_2.conda
https://repo.anaconda.com/pkgs/main/osx-64/mkl_random-1.2.2-py37hb2f4e1b_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/numpy-1.20.3-py37h4b4dc7a_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/py-opencv-3.4.2-py37h7c891bd_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/pywavelets-1.1.1-py37haf1e3a3_2.conda
https://repo.anaconda.com/pkgs/main/osx-64/scipy-1.7.1-py37h88652d9_2.conda
https://repo.anaconda.com/pkgs/main/osx-64/tifffile-2020.10.1-py37h0cf3a3e_2.conda
https://repo.anaconda.com/pkgs/main/osx-64/opencv-3.4.2-py37h6fd60c2_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/scikit-image-0.18.1-py37hb2f4e1b_0.conda
